In [1]:
pip install tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


Create tensors


In [8]:
a = tf.constant(5)
print(a)
v = tf.constant([1,2,3,4])
print (v)
m = tf.constant([[1,2],[3,4]])
print(m)
t3 =tf.constant([[[1,2,],[3,4]],[[5,6],[7,8]]])
print(t3)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [16]:
a = tf.constant([10,20,30])
b = tf.constant([50,60,70])
print(a+b)
print(b-a)
print(a*b)
print(b/a)


tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)
tf.Tensor([40 40 40], shape=(3,), dtype=int32)
tf.Tensor([ 500 1200 2100], shape=(3,), dtype=int32)
tf.Tensor([5.         3.         2.33333333], shape=(3,), dtype=float64)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)


In [17]:
a = tf.constant([10,20,20])
print(a.dtype,a.shape,tf.rank(a))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)


Numpy array to tensor

In [18]:
import numpy as np
np_array = np.array([[1,2,3],[4,5,6]])
tensor = tf.convert_to_tensor(np_array)
print(tensor)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
